name: bunker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Управление состоянием
  flutter_bloc: ^9.1.0        # Для реализации BLoC паттерна
  equatable: ^2.0.5           # Для сравнения объектов без необходимости переопределять equals
  provider: ^6.0.5            # Для внедрения зависимостей

  # Сеть и подключение
  web_socket_channel: ^3.0.2  # Для WebSocket соединений
  network_info_plus: ^6.1.3   # Для получения информации о сети
  multicast_dns: ^0.3.2       # Для обнаружения сервисов по сети
  connectivity_plus: ^6.1.3   # Для проверки состояния подключения

  # Хранение данных
  hive: ^2.2.3                # Легковесная NoSQL база данных
  hive_flutter: ^1.1.0        # Flutter-интеграция для Hive
  shared_preferences: ^2.0.18 # Для хранения простых настроек

  # Утилиты
  get_it: ^8.0.3              # Сервис-локатор для внедрения зависимостей
  injectable: ^2.1.0          # Генерация кода для dependency injection
  json_annotation: ^4.8.0     # Аннотации для сериализации JSON
  uuid: ^4.5.1                # Генерация UUID
  intl: ^0.19.0               # Интернационализация и форматирование
  logger: ^2.5.0              # Логирование

  # UI и стилизация
  google_fonts: ^6.2.1        # Шрифты Google
  flutter_svg: ^2.0.5         # Работа с SVG
  cached_network_image: ^3.4.1 # Кэширование изображений
  lottie: ^3.3.1              # Анимации Lottie
  animated_text_kit: ^4.2.2   # Анимации текста


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.15        # Генерация кода
  json_serializable: ^6.9.0    # Генерация кода для JSON сериализации
  hive_generator: ^2.0.0       # Генерация кода для Hive
  injectable_generator: ^2.6.2 # Генерация кода для injectable
  flutter_launcher_icons: ^0.14.3 # Генерация иконок приложения
  flutter_native_splash: ^2.4.5 # Экран загрузки

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/data/
